import type { Metadata } from "next";
import localFont from 'next/font/local'

const ggSans = localFont({ src: 'discord/fonts/gg-sans.ttf' })

import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ggSans.className}>{children}</body>
    </html>
  );
}
